spring:
  application:
    name: filter
  cloud:
    stream:
      bindings:
        output:
          destination: ${output:log}
        input:
          destination: tick-tock
          consumer:
            durableSubscription: true
management.security.enabled: false